AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: CommandLog local development foundation

Resources:
  ListDecksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: commandlog-local-list-decks
      CodeUri: ../backend/functions/mtg-app-list-decks/
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          APP_END: local
          AWS_ENDPOINT_URL: http://host.docker.internal:4566
          AWS_REGION: ca-central-1
          STATE_TABLE: commandlog_local_deck_state
          USERS_TABLE: commandlog_local_user_profile